ui: tape
browsers:
  - name: chrome
    version: latest
  - name: ie
    version: 8..latest
  - name: firefox
    version: 25..latest
  - name: opera
    version: 11..latest
  - name: safari
    version: 6..latest